version: '3.8'

services:
  api:
    build: .
    ports:
      - "9006:9006"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - rex_shared_network

networks:
  rex_shared_network:
    external: true
    name: rex_shared_network
